
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef MIOSIXLOGOHOMEPAGE_H
#define MIOSIXLOGOHOMEPAGE_H

#include "mxgui/image.h"

extern const mxgui::Image miosixlogohomepage;

#endif //MIOSIXLOGOHOMEPAGE_H
